name: Django CI/CD Pipeline

on:
  pull_request:
    branches:
      - ci-testing-ss

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create media directory
        run: |
          mkdir -p jumcms/media

      - name: Set up environment variables
        run: |
          echo "SECRET_KEY=django-insecure-+5@v2_e=w9+%xz3xmr&inw-0c%af4r8e&uu+__0y27x6ysf^o-" >> $GITHUB_ENV
          echo "DEBUG=True" >> $GITHUB_ENV

      - name: Run database migrations
        run: |
          python jumcms/manage.py makemigrations
          python jumcms/manage.py migrate

      - name: Run tests
        run: |
          python jumcms/manage.py test